// src/pages/auth/Login.vue
<template>
  <div class="auth-container">
    <v-container class="fill-height py-0">
      <v-row>
        <v-col cols="10"  md="8" lg="6" xl="4" offset="1" offset-sm="1" offset-md="2" offset-lg="3" offset-xl="4" class="d-flex align-center justify-center" style="min-height: 100vh;">
          <v-card elevation="12" class="w-100 px-5 py-4 px-md-15 py-md-15 rounded-xl">
            <div class="auth-header text-center mb-10">
              <div class="logo">
                <v-icon size="52" color="white">mdi-church</v-icon>
              </div>
              <h1 class="text-h5 font-weight-bold mt-4 mb-2">Church Manager</h1>
              <p class="text-body-2 text-medium-emphasis">Faça login para continuar</p>
            </div>

            <v-form @submit.prevent="handleLogin" class="auth-form">
              <v-text-field
                v-model="email"
                label="E-mail"
                type="email"
                placeholder="seu@email.com"
                prepend-inner-icon="mdi-email"
                variant="outlined"
                density="comfortable"
                required
                class="mb-4"
              />

              <v-text-field
                v-model="password"
                :type="showPassword ? 'text' : 'password'"
                label="Senha"
                placeholder="••••••••"
                prepend-inner-icon="mdi-lock"
                :append-inner-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
                @click:append-inner="showPassword = !showPassword"
                variant="outlined"
                density="comfortable"
                required
                class="mb-4"
              />

              <v-btn
                type="submit"
                color="primary"
                size="large"
                block
                class="mb-4"
                :loading="loading"
              >
                <span>Entrar</span>
                <v-icon end>mdi-arrow-right</v-icon>
              </v-btn>
            </v-form>

            <div class="text-center mt-10">
              <p class="text-body-2 text-medium-emphasis mb-2">Primeira vez aqui?</p>
              <v-btn
                variant="text"
                color="primary"
                @click="goToOnboarding"
              >
                Criar nova organização
              </v-btn>
            </div>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { authCustomApi } from './auth.api'

const router = useRouter()
const $api = authCustomApi()

const email = ref('')
const password = ref('')
const showPassword = ref(false)
const loading = ref(false)

const handleLogin = async () => {
  loading.value = true
  try {
    await $api.login({ email: email.value, password: password.value })
    
    router.push('/dashboard')
  } catch (error) {
    console.error('Erro no login:', error)
  } finally {
    loading.value = false
  }
}

const goToOnboarding = () => {
  router.push('/auth/onboarding')
}
</script>

<style scoped>
.auth-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #1e3a5f 0%, #2c5282 50%, #4299e1 100%);
}

.auth-header .logo {
  width: 72px;
  height: 72px;
  background: linear-gradient(135deg, #1e3a5f 0%, #4299e1 100%);
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 16px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

</style>

// src/pages/Login.tsx
import { Church, Mail, Lock, Eye, ArrowRight } from 'lucide-react'

function Login() {
  return (
    <>
      <main className="relative min-h-screen min-w-screen flex items-center justify-center p-4 bg-[#0f172a]">
        <div className="absolute inset-0 bg-gradient-to-tr from-[#0f172a] via-[#1e293b] to-[#0f172a] opacity-100"></div>

        <div className="relative z-10 bg-white rounded-2xl shadow-2xl px-8 py-12 w-full max-w-[400px] flex flex-col items-center">
          <div className="bg-primary p-3 rounded-xl mb-4 text-white">
            <Church size={52} />
          </div>

          <h1 className="text-xl font-bold text-[#1e293b]">Church Manager</h1>
          <p className="text-gray-400 text-xs mb-8">Faça login para continuar</p>

          <form className="w-full space-y-4">
            <div className="space-y-1">
              <label className="text-xs font-bold text-gray-600 ml-1">E-mail</label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                  <Mail className="w-4 h-4" />
                </div>
                <input type="email" placeholder="seu@email.com"
                  className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition text-sm" />
              </div>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-gray-600 ml-1">Senha</label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400">
                  <Lock className="w-4 h-4" />
                </div>
                <input type="password" placeholder="********"
                  className="w-full pl-10 pr-10 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition text-sm" />
                <div className="absolute inset-y-0 right-0 pr-3 flex items-center cursor-pointer text-gray-400 hover:text-gray-600">
                  <Eye className="w-4 h-4" />
                </div>
              </div>
            </div>

            <button type="submit" className="w-full bg-primary text-white py-2 rounded-lg hover:bg-primary/80 active:bg-primary/90 transition-all flex items-center justify-center gap-2 text-sm">
              Entrar
              <ArrowRight className="w-4 h-4" />
            </button>
          </form>

          <div className="mt-10 text-center space-y-2">
            <p className="text-xs text-gray-400">Primeira vez aqui?</p>
            <a href="#" className="text-sm font-bold text-gray-700 hover:text-blue-900 block">Criar nova organização</a>
          </div>
        </div>
      </main>
    </>
  )
}

export default Login
